---
language: ruby
bundler_args: --without development
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
services:
  - docker
matrix:
  fast_finish: true
  include:
  - rvm: 2.1
    env: PUPPET_INSTALL_TYPE=agent BEAKER_set=docker/centos-6-x64
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.1
    env: PUPPET_INSTALL_TYPE=agent BEAKER_set=docker/centos-7-x64
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="~> 4.0.0" STRICT_VARIABLES=yes
  - rvm: 2.4
    env: PUPPET_GEM_VERSION="~> 5.0.0" STRICT_VARIABLES=yes
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
notifications:
  email: false
